//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesLivraria.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FivesLivraria.Security.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta de usuário está travada..
        /// </summary>
        internal static string BlockedAccount {
            get {
                return ResourceManager.GetString("BlockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudança de senha cancelada por falha de validação da senha atual..
        /// </summary>
        internal static string CancelChangePassword {
            get {
                return ResourceManager.GetString("CancelChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string de conexão não pode ser vazia..
        /// </summary>
        internal static string ConnectionStringError {
            get {
                return ResourceManager.GetString("ConnectionStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível travar a conta do usuário..
        /// </summary>
        internal static string ErrorBlockAccount {
            get {
                return ResourceManager.GetString("ErrorBlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível atualizar o contador de falhas e janela..
        /// </summary>
        internal static string ErrorCounterFailUpdate {
            get {
                return ResourceManager.GetString("ErrorCounterFailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro ocorreu. Consulte o Log de Eventos para maiores detalhes..
        /// </summary>
        internal static string GeneralExceptionMessage {
            get {
                return ResourceManager.GetString("GeneralExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível decodificar uma senha hash..
        /// </summary>
        internal static string HashCodeError {
            get {
                return ResourceManager.GetString("HashCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta de recuperação de senha incorreta.
        /// </summary>
        internal static string IncorrectPasswordAnswer {
            get {
                return ResourceManager.GetString("IncorrectPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta de usuário não encontrada..
        /// </summary>
        internal static string LoginNotFound {
            get {
                return ResourceManager.GetString("LoginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de senha não suportado..
        /// </summary>
        internal static string PasswordFormatError {
            get {
                return ResourceManager.GetString("PasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de senhas desabilitada..
        /// </summary>
        internal static string PasswordRecoveryDisabled {
            get {
                return ResourceManager.GetString("PasswordRecoveryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reinicialização da senha não está habilitada..
        /// </summary>
        internal static string PasswordResetDisabled {
            get {
                return ResourceManager.GetString("PasswordResetDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário &quot;{0}&quot; já está no perfil &quot;{1}&quot;..
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um perfil com usuários vinculados..
        /// </summary>
        internal static string RoleConstraint {
            get {
                return ResourceManager.GetString("RoleConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um perfil com este nome..
        /// </summary>
        internal static string RoleExists {
            get {
                return ResourceManager.GetString("RoleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode haver vírgula no nome do perfil..
        /// </summary>
        internal static string RoleNameError {
            get {
                return ResourceManager.GetString("RoleNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil não existe..
        /// </summary>
        internal static string RoleNotExists {
            get {
                return ResourceManager.GetString("RoleNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil &quot;{0}&quot; não foi encontrado..
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na comunicação com o servidor.
        ///
        ///Action: {0} 
        ///
        ///Exception: {1}.
        /// </summary>
        internal static string ServerCommunicationError {
            get {
                return ResourceManager.GetString("ServerCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode haver vírgula no nome de usuário..
        /// </summary>
        internal static string UsernameError {
            get {
                return ResourceManager.GetString("UsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Usuário &quot;{0}&quot; não encontrado no perfil &quot;{1}&quot;..
        /// </summary>
        internal static string UserNotFoundInRole {
            get {
                return ResourceManager.GetString("UserNotFoundInRole", resourceCulture);
            }
        }
    }
}
